### ISSUE TITLE
A problem occurred while executing the rendering code

### ISSUE THREAD

**Issue by ROJ1999** [gmum/ViewingDirectionGaussianSplatting#3]
<img width="753" alt="Snipaste_2024-03-06_16-25-44" src="https://github.com/gmum/ViewingDirectionGaussianSplatting/assets/49748395/d661bd83-763f-4ccf-b40b-04363442c70c">

**Comment by JDihlmann** [comment]
See https://github.com/gmum/ViewingDirectionGaussianSplatting/pull/2
