### ISSUE TITLE
Release date for hash-based encoding. 

### ISSUE THREAD

**Issue by gaetan-landreau** [gmum/ViewingDirectionGaussianSplatting#5]
Hi ! 
Closely followed over the past few months the different upgrades you've made on your paper ! Thank you for you work, your contributions truly helped me to render transparents and reflective surfaces. 🤗

I've seen on the very last version of your paper you published on ArXiV that you were now using hash encoding from InstantNGP as input for the MLP you designed. Is there any plan to release such a corresponding code ? 

Thanks for you help, 

Gaétan.

**Comment by anonymous-github-8ab1cv** [comment]
+1

**Comment by wMito** [comment]
Hi!

Thank you so much for your kind words and so sorry for such a late response. I just pushed hash grid and tinycuda additions to main here :)
